#add yubikey later
keys:
  - &admin_cdockter age1jpuytk9u84lvw269pceeq2qh9g9ayaurezc0ja7ffj4w333teqaqt2d7p7
creation_rules:
  - path_regex: system/secrets/secrets.yaml$
    key_groups:
      - age:
          - *admin_cdockter
