# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config }:
{
  enableRedistributableFirmware = true;
  cpu.intel = {
    updateMicrocode = true;
  };
  nvidia = {
    modesetting.enable = true;
    package = config.boot.kernelPackages.nvidiaPackages.beta;
    open = true;
    powerManagement = {
      enable = true;
      # finegrained = true;
    };
    prime = {
      sync.enable = true;
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:0:1:0";
      #pci@0000:01:00.0
    };
  };
}
