
{ config, pkgs,lib, ... }:
  {
    home.packages= with pkgs;[
      polkit_gnome
      libva-utils
      fuseiso
      udiskie
      gnome.adwaita-icon-theme
      gnome.gnome-themes-extra
      nvidia-vaapi-driver
      gsettings-desktop-schemas
      swaynotificationcenter
      wlr-randr
      ydotool
      wl-clipboard
      swayidle
      swaylock
      wofi
      swww
      grim
      xdg-utils
      lshw
      xdg-desktop-portal
      xdg-desktop-portal-gtk
      qt5.qtwayland
      qt6.qmake
      qt6.qtwayland
      adwaita-qt
      adwaita-qt6
      waybar
      wayland-protocols
      wayland-utils
      pavucontrol
      wlroots
      upower
      gtkmm3
      dbus
      power-profiles-daemon
    ];
  }
