# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
#clean me fans spongebob
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/be07ad47-b72c-4112-a912-b0869f4b8b8b";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-9410848d-3f81-429f-a6bd-773f1454acc6".device = "/dev/disk/by-uuid/9410848d-3f81-429f-a6bd-773f1454acc6";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A3D8-BF1E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/Drives/EHDD" = {
    device = "/dev/disk/by-uuid/25cebdad-13ba-4676-8272-61d72cc168a8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."EHDD".device = "/dev/disk/by-uuid/13ab5b6b-79f0-49a6-864f-c2239e5f8313";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u4u5.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
